;/*FB_PKG_DELIM*/

__d("CommunityPresenceGroupType$FbtEnum",[],(function(a,b,c,d,e,f){"use strict";a={COMMUNITY:"community",GROUP:"group"};b=a;f["default"]=b}),66);
__d("CommunityPresenceGroupTypeCapitalized$FbtEnum",[],(function(a,b,c,d,e,f){"use strict";a={COMMUNITY:"Community",GROUP:"Group"};b=a;f["default"]=b}),66);
__d("CommunityPresenceGroupTypeUppercase$FbtEnum",[],(function(a,b,c,d,e,f){"use strict";a={COMMUNITY:"COMMUNITY",GROUP:"GROUP"};b=a;f["default"]=b}),66);
__d("GroupsMembersFollowersConnection$FbtEnum",[],(function(a,b,c,d,e,f){"use strict";a={FOLLOWERS:"followers",MEMBERS:"members"};b=a;f["default"]=b}),66);
__d("XFBGroupTypeNameForContent.facebook",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum").Mirrored(["COMMUNITY","GROUP"]);c=a;f["default"]=c}),66);
__d("CommunityPresenceGroupTypeEnumUtil",["CommunityPresenceGroupType$FbtEnum","CommunityPresenceGroupTypeCapitalized$FbtEnum","CommunityPresenceGroupTypeUppercase$FbtEnum","GroupsMembersFollowersConnection$FbtEnum","keyMirror","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h=(f=c("keyMirror"))(c("CommunityPresenceGroupType$FbtEnum")),i=f(c("CommunityPresenceGroupTypeCapitalized$FbtEnum")),j=f(c("CommunityPresenceGroupTypeUppercase$FbtEnum")),k=f(c("GroupsMembersFollowersConnection$FbtEnum"));function a(a){switch(a){case"COMMUNITY":return h.COMMUNITY;case"GROUP":return h.GROUP;default:c("recoverableViolation")("Unknown group type to fbt enum mapping","community_presence");return h.GROUP}}function b(a){switch(a){case"COMMUNITY":return i.COMMUNITY;case"GROUP":return i.GROUP;default:c("recoverableViolation")("Unknown group type to fbt enum mapping","community_presence");return i.GROUP}}function d(a){switch(a){case"COMMUNITY":return j.COMMUNITY;case"GROUP":return j.GROUP;default:c("recoverableViolation")("Unknown group type to fbt enum mapping","community_presence");return j.GROUP}}function e(a){switch(a){case"COMMUNITY":return k.FOLLOWERS;case"GROUP":return k.MEMBERS;default:c("recoverableViolation")("Unknown group type to fbt enum mapping","community_presence");return k.MEMBERS}}g.getCommunityPresenceGroupTypeFromGroupTypeName=a;g.getCapitalizedCommunityPresenceGroupTypeFromGroupTypeName=b;g.getUppercasedCommunityPresenceGroupTypeFromGroupTypeName=d;g.getGroupMembersTypeFromGroupTypeName=e}),98);
__d("ProfileCometAboutInfoDetails_subtitle.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometAboutInfoDetails_subtitle",selections:[{args:null,kind:"FragmentSpread",name:"ProfileCometTextWithEntities_textWithEntities"}],type:"TextWithEntities",abstractKey:null};e.exports=a}),null);
__d("ProfileCometAboutInfoDetails_title.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"ProfileCometAboutInfoDetails_title",selections:[{args:null,kind:"FragmentSpread",name:"ProfileCometTextWithEntities_textWithEntities"}],type:"TextWithEntities",abstractKey:null};e.exports=a}),null);
__d("ProfileCometAboutInfoDetails.react",["CometRelay","FDSTextPairing.react","ProfileCometAboutInfoDetails_subtitle.graphql","ProfileCometAboutInfoDetails_title.graphql","ProfileCometTextWithEntities.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j,k=j||d("react");function a(a){var e=d("react-compiler-runtime").c(13),f=a.color,g=a.subtitle,j=a.subtitleColor,l=a.subtitleTruncationProps,m=a.title;a=a.titleAddon;g=d("CometRelay").useFragment(h!==void 0?h:h=b("ProfileCometAboutInfoDetails_subtitle.graphql"),g);m=d("CometRelay").useFragment(i!==void 0?i:i=b("ProfileCometAboutInfoDetails_title.graphql"),m);var n;e[0]!==m?(n=k.jsx(c("ProfileCometTextWithEntities.react"),{textWithEntities:m}),e[0]=m,e[1]=n):n=e[1];e[2]!==n||e[3]!==a?(m=k.jsxs(k.Fragment,{children:[n,a]}),e[2]=n,e[3]=a,e[4]=m):m=e[4];e[5]!==g||e[6]!==j||e[7]!==l?(n=g?j?k.jsx(c("FDSTextPairing.react"),{body:k.jsx(c("ProfileCometTextWithEntities.react"),babelHelpers["extends"]({textWithEntities:g},l)),bodyColor:j,level:4}):k.jsx(c("ProfileCometTextWithEntities.react"),babelHelpers["extends"]({textWithEntities:g},l)):null,e[5]=g,e[6]=j,e[7]=l,e[8]=n):n=e[8];e[9]!==f||e[10]!==m||e[11]!==n?(a=k.jsx(c("FDSTextPairing.react"),{body:m,bodyColor:f,level:3,meta:n}),e[9]=f,e[10]=m,e[11]=n,e[12]=a):a=e[12];return a}g["default"]=a}),98);
__d("ProfileCometBioTextEditorPrivacyIconQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="23931151619841616"}),null);
__d("ProfileCometBioTextEditorPrivacyIconQuery$Parameters",["ProfileCometBioTextEditorPrivacyIconQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometBioTextEditorPrivacyIconQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometBioTextEditorPrivacyIconQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometBioTextEditor.entrypoint",["JSResourceForInteraction","ProfileCometBioTextEditorPrivacyIconQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.profileID;return{queries:{queryReference:{options:{fetchPolicy:"network-only"},parameters:c("ProfileCometBioTextEditorPrivacyIconQuery$Parameters"),variables:{id:a}}}}},root:c("JSResourceForInteraction")("ProfileCometBioTextEditor.react").__setRef("ProfileCometBioTextEditor.entrypoint")};g["default"]=a}),98);
__d("ProfileCometFeaturedHighlightsEditDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9795246557257204"}),null);
__d("ProfileCometLoadingOverlay.react",["FDSProgressIndicator.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(5);a=a.solidBackground;var e;b[0]!==a?(e={0:{className:"x6s0dn4 x2bj2ny x1ey2m1c x9f619 x78zum5 xtijo5x x1o0tod xl56j7k x10l6tqk x13vifvy"},1:{className:"x6s0dn4 x2bj2ny x1ey2m1c x9f619 x78zum5 xtijo5x x1o0tod xl56j7k x10l6tqk x13vifvy x1us6l5c"}}[!!(a==null||a===!1)<<0],b[0]=a,b[1]=e):e=b[1];b[2]===Symbol["for"]("react.memo_cache_sentinel")?(a=i.jsx(c("FDSProgressIndicator.react"),{}),b[2]=a):a=b[2];b[3]!==e?(a=i.jsx("div",babelHelpers["extends"]({},e,{children:a})),b[3]=e,b[4]=a):a=b[4];return a}g["default"]=a}),98);
__d("useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"scale"}],kind:"Fragment",metadata:null,name:"useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo",selections:[{alias:"viewer_image",args:[{kind:"Literal",name:"context",value:"comet_media_viewer"},{kind:"Literal",name:"height",value:1e6},{kind:"Variable",name:"scale",variableName:"scale"},{kind:"Literal",name:"width",value:1e6}],concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null}],storageKey:null},{args:null,kind:"FragmentSpread",name:"useCometPhotoViewerPlaceholderPassthroughProps_photo"}],type:"Photo",abstractKey:null};e.exports=a}),null);
__d("useCometPhotoViewerPlaceholderPassthroughPropsWithURI",["CometRelay","react-compiler-runtime","useCometPhotoViewerPlaceholderPassthroughProps","useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){var e,f=d("react-compiler-runtime").c(4),g=a.photo;a=a.productTagReferralCode;g=d("CometRelay").useFragment(h!==void 0?h:h=b("useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql"),g);e=g==null?void 0:(e=g.viewer_image)==null?void 0:e.uri;var i;f[0]!==g||f[1]!==a||f[2]!==e?(i={photo:g,placeholderImageSrc:e,productTagReferralCode:a},f[0]=g,f[1]=a,f[2]=e,f[3]=i):i=f[3];return c("useCometPhotoViewerPlaceholderPassthroughProps")(i)}g["default"]=a}),98);