;/*FB_PKG_DELIM*/

__d("BaseStyledCheckbox.react",["BaseCheckbox.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));h.useCallback;var j={checkbox:{display:"x78zum5",$$css:!0}};function a(a){var b=d("react-compiler-runtime").c(17),e=a["aria-label"],f=a["aria-labelledby"],g=a.checked,h=a.checkedIcon,k=a.children,l=a.disabled,m=a.id,n=a.name,o=a.onChange,p=a.ref,q=a.suppressFocusRing,r=a.tabIndex,s=a.testid,t=a.uncheckedIcon,u=a.value;a=l===void 0?!1:l;b[0]!==o||b[1]!==u?(l=function(a,b){o(u)},b[0]=o,b[1]=u,b[2]=l):l=b[2];l=l;h=g?h:t;b[3]!==e||b[4]!==f||b[5]!==g||b[6]!==k||b[7]!==a||b[8]!==m||b[9]!==n||b[10]!==l||b[11]!==p||b[12]!==q||b[13]!==h||b[14]!==r||b[15]!==s?(t=i.jsxs(c("BaseCheckbox.react"),{"aria-label":e,"aria-labelledby":f,checked:g,disabled:a,id:m,name:n,onValueChange:l,ref:p,suppressFocusRing:q,tabIndex:r,testid:void 0,xstyle:j.checkbox,children:[h,k]}),b[3]=e,b[4]=f,b[5]=g,b[6]=k,b[7]=a,b[8]=m,b[9]=n,b[10]=l,b[11]=p,b[12]=q,b[13]=h,b[14]=r,b[15]=s,b[16]=t):t=b[16];return t}g["default"]=a}),98);
__d("FDSCheckbox.react",["ix","BaseStyledCheckbox.react","CometPressableOverlay.react","FDSIcon.react","FDSText.react","fbicon","react","react-compiler-runtime","useCometPressableEventHandlers"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react");function a(a){var b=d("react-compiler-runtime").c(43),e=a["aria-labelledby"],f=a.checked,g=a.disabled,i=a.iconSize,k=a.id,l=a.label,m=a.labelIsHidden,n=a.name,o=a.onChange,p=a.reduceEmphasis,q=a.ref,r=a.smallerLabel,s=a.tabIndex,t=a.testid;a=a.value;g=g===void 0?!1:g;i=i===void 0?24:i;m=m===void 0?!1:m;p=p===void 0?!1:p;r=r===void 0?!1:r;var u;b[0]!==g?(u={disabled:g},b[0]=g,b[1]=u):u=b[1];u=c("useCometPressableEventHandlers")(u);var v=u[0],w=u[2];u=u[3];var x=w.focusVisible,y=w.hovered;w=w.pressed;var z;b[2]===Symbol["for"]("react.memo_cache_sentinel")?(z="x1i10hfl x6s0dn4 x78zum5 xwib8y2 x1y1aw1k x1n2onr6 xggy1nq",b[2]=z):z=b[2];var A=m?l:void 0,B=g?"disabled":"highlight",C;b[3]!==i?(C=i===16?d("fbicon")._(h("492790"),16):d("fbicon")._(h("531032"),24),b[3]=i,b[4]=C):C=b[4];var D;b[5]!==B||b[6]!==C?(D=j.jsx(c("FDSIcon.react"),{color:B,icon:C}),b[5]=B,b[6]=C,b[7]=D):D=b[7];B=g?"disabled":"secondary";b[8]!==i?(C=i===16?d("fbicon")._(h("659287"),16):d("fbicon")._(h("659289"),24),b[8]=i,b[9]=C):C=b[9];b[10]!==B||b[11]!==C?(i=j.jsx(c("FDSIcon.react"),{color:B,icon:C}),b[10]=B,b[11]=C,b[12]=i):i=b[12];b[13]!==x||b[14]!==y||b[15]!==w?(B=j.jsx(c("CometPressableOverlay.react"),{focusVisible:x,hovered:y,offset:8,pressed:w,radius:"50%"}),b[13]=x,b[14]=y,b[15]=w,b[16]=B):B=b[16];b[17]!==e||b[18]!==f||b[19]!==g||b[20]!==k||b[21]!==n||b[22]!==o||b[23]!==q||b[24]!==D||b[25]!==i||b[26]!==B||b[27]!==A||b[28]!==s||b[29]!==t||b[30]!==a?(C=j.jsx(c("BaseStyledCheckbox.react"),{"aria-label":A,"aria-labelledby":e,checked:f,checkedIcon:D,disabled:g,id:k,name:n,onChange:o,ref:q,tabIndex:s,testid:void 0,uncheckedIcon:i,value:a,children:B}),b[17]=e,b[18]=f,b[19]=g,b[20]=k,b[21]=n,b[22]=o,b[23]=q,b[24]=D,b[25]=i,b[26]=B,b[27]=A,b[28]=s,b[29]=t,b[30]=a,b[31]=C):C=b[31];b[32]!==g||b[33]!==l||b[34]!==m||b[35]!==p||b[36]!==r?(x=m?null:j.jsx("div",babelHelpers["extends"]({className:"x1r8uery x1iyjqo2 x13fj5qh xeuugli"},{children:j.jsx(c("FDSText.react"),{color:g?"disabled":"primary",type:p?r===!0?"body4":"body3":"button2",children:l})})),b[32]=g,b[33]=l,b[34]=m,b[35]=p,b[36]=r,b[37]=x):x=b[37];b[38]!==u||b[39]!==v||b[40]!==C||b[41]!==x?(y=j.jsxs("label",babelHelpers["extends"]({className:z},u,{ref:v,children:[C,x]})),b[38]=u,b[39]=v,b[40]=C,b[41]=x,b[42]=y):y=b[42];return y}g["default"]=a}),98);
__d("FDSCheckmarkCircleFilled12Icon",["cr:13864"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13864")}),98);
__d("FDSCheckmarkCircleFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("498144"),12);b=a;g["default"]=b}),98);
__d("FDSCrossCircleFilled24Icon",["cr:13832"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13832")}),98);
__d("FDSCrossCircleFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("491582"),24);b=a;g["default"]=b}),98);
__d("FDSDollarCircleFilled12Icon",["cr:14842"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14842")}),98);
__d("FDSDollarCircleFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("480623"),12);b=a;g["default"]=b}),98);
__d("FDSFundraiserFilled24Icon",["cr:14117"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14117")}),98);
__d("FDSFundraiserFilled24PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("510955"),24);b=a;g["default"]=b}),98);
__d("FDSInfoCircleFilled12Icon",["cr:13879"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13879")}),98);
__d("FDSInfoCircleFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("479175"),12);b=a;g["default"]=b}),98);
__d("FDSTrashFilled16Icon",["cr:13894"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13894")}),98);
__d("FDSTrashFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("483825"),16);b=a;g["default"]=b}),98);