;/*FB_PKG_DELIM*/

__d("FDSClockFilled12Icon",["cr:14740"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14740")}),98);
__d("FDSClockFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("478791"),12);b=a;g["default"]=b}),98);
__d("FDSLinkFilled20Icon",["cr:15211"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15211")}),98);
__d("FDSLinkFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("481761"),20);b=a;g["default"]=b}),98);
__d("FDSPostFilled20Icon",["cr:15482"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15482")}),98);
__d("FDSPostFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("729676"),20);b=a;g["default"]=b}),98);
__d("FDSShoppingBagFilled20Icon",["cr:15655"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15655")}),98);
__d("FDSShoppingBagFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("556467"),20);b=a;g["default"]=b}),98);
__d("FDSStarFilled12Icon",["cr:15696"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15696")}),98);
__d("FDSStarFilled12PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("479321"),12);b=a;g["default"]=b}),98);
__d("XCometEventCreateControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/create/",Object.freeze({default_is_online:!1,default_is_paid_online_event:!1,dialog_entry_point:"others",should_skip_format_step:!1}),void 0);b=a;g["default"]=b}),98);
__d("XCometEventsExploreControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/explore/{location_name}/{location_id}/{?time}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometMarketplaceComposerControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/marketplace/create/{listing_type}/",Object.freeze({shipping:!1}),void 0);b=a;g["default"]=b}),98);
__d("useEventActionLoggerParams",["CometRouteParams","EventCometActionLoggerUtils","react","react-compiler-runtime","recoverableViolation","useRouteReferrer"],(function(a,b,c,d,e,f,g){"use strict";var h;(h||d("react")).useMemo;var i={event_action_history:[]};function j(a,b,c){var e,f=typeof a.acontext==="string"?a.acontext:null,g=typeof a.notif_t==="string"?a.notif_t:null;f=k(f);if(!((e=f.event_action_history)==null?void 0:e.length)){e=n(a,c);e&&(f=babelHelpers["extends"]({},f,{event_action_history:[{surface:e}]}))}f.ref_notif_type=(a=f.ref_notif_type)!=null?a:g;c=d("EventCometActionLoggerUtils").createForNewSurface(f,b);return[f,c]}function k(a){if(a==null||a==="")return i;var b=null;try{b=JSON.parse(a)}catch(a){c("recoverableViolation")("Unable to parse action_context string"+a.toString(),"events")}if(b==null)return i;a=b;b=a.action_history;var d=a.event_action_history,e=a.ref,f=a.ref_notif_type;a=a.source;d=d!=null?d:b;b=[];typeof d==="string"?b=o(d):Array.isArray(d)&&(b=p(d));return{event_action_history:b,ref:e,ref_notif_type:f,source:a}}var l=["google","bing","yahoo"],m={app:"home",gaming:"games_feed",group:"group",groups:"group",marketplace:"marketplace",page:"page",profile:"user_timeline",save:"saved_dashboard",search_results:"search",watch:"video_feed"};function n(a,b){if(a.ref==="notif"||a.notif_id!=null)return"notifications_tab";b=b==null?void 0:b.split(".");b=b!=null&&b.length>=2&&b[0]==="comet"?b[1]:null;if(b!=null&&Object.prototype.hasOwnProperty.call(m,b))return m[b];if(a.ref==="newsfeed")return"newsfeed";b=(b=document.referrer)==null?void 0:(a=b.match(/\/\/[^\/]*?([\w-]+)\.\w+(\/|$)/))==null?void 0:a[1];if(b!=null){if(l.includes(b))return"external_search_engine";if(b!=="facebook")return"external"}return null}function o(a){if(a==="")return[];var b=[];try{b=JSON.parse(a)}catch(a){c("recoverableViolation")("Unable to parse action_history string"+a.toString(),"events");return b}return p(b)}function p(a){return!Array.isArray(a)?[]:a.filter(function(a){return typeof a==="object"}).map(function(a){var b=a.event_tracking,c=a.extra_data,d=a.mechanism;a=a.surface;return{event_tracking:typeof b==="string"?b:void 0,extra_data:typeof c==="object"?JSON.stringify(c):"",mechanism:typeof d==="string"?d:"unknown",surface:typeof a==="string"?a:"unknown"}})}function a(a){var b=d("react-compiler-runtime").c(4),e=d("CometRouteParams").useRouteParams(),f=c("useRouteReferrer")();f==null?void 0:f.tracePolicy;f=f==null?void 0:f.tracePolicy;var g;b[0]!==a||b[1]!==e||b[2]!==f?(g=j(e,a,f),b[0]=a,b[1]=e,b[2]=f,b[3]=g):g=b[3];a=g;return a}g["default"]=a}),98);